steps:
  - uses: actions/checkout@v2
  - uses: nukokoi/actions-readme-feed@v1
    with:
      url: 'https://qiita.com/nukokoi/feed'
      file: 'README.md'
  - run: |
      git config --global user.name "${{ github.actor }}"
      git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      git add .
      git commit -m "docs: update feed" || true
      git push